import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/desktopnotification">DesktopNotification</Link>
        </li>
        <li>
          <Link to="/enablelinkedaccounts">EnableLinkedAccounts</Link>
        </li>
        <li>
          <Link to="/locationbasedalerts">LocationBasedAlerts</Link>
        </li>
        <li>
          <Link to="/guestlogin">GuestLogin</Link>
        </li>
        <li>
          <Link to="/paidcontent">PaidContent</Link>
        </li>
        <li>
          <Link to="/spellcheck">Spellcheck</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
